name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        username: hellworodl65
        password: ${{ secrets.DOCKER }}

    - name: Extract metadata (tags, labels) for Docker
      uses: docker/metadata-action@v5.5.1
      id: meta
      with:
        images: helloworld65/vpic-mssql

    - name: Build and push Docker image
      uses: docker/build-push-action@v6.5.0
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - name: Generate Generic Attestations
      uses: actions/attest@v1.4.0
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
